# Generated by Django 5.0.4 on 2024-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank-profile.svg', null=True, upload_to='profile_pic'),
        ),
    ]
